### PR TITLE
Switch tests to xqsuite

### PR DESCRIPTION
**Pull request by joewiz**
This PR adapts the original java-based tests to use [xqsuite](https://exist-db.org/exist/apps/doc/xqsuite) and deletes the java tests, with the aim of running the tests via Maven and in CI.

### CODE REVIEW

**Comment by adamretter** [comment]
@joewiz Looks good. Do you mind if I push some commits to this PR to add the parts needed to have it run via XQSuite in Maven etc?

**Comment by joewiz** [comment]
@adamretter Not at all! Please push and modify as you see fit. Thank you!

**Comment by joewiz** [comment]
@adamretter Doh! I should've given the test module the `xqm` extension, since it's a library module. Would it be possible for you to make this change in your commits?

**Comment by adamretter** [comment]
Tests will now run with `mvn verify` and I added CI for that too :-)

**Comment by joewiz** [comment]
@adamretter Cool! `mvn verify` runs like a charm. 

The xqsuite has one remaining problem on [line 52](https://github.com/eXist-db/crypto-exist-java-lib/pull/39/commits/f453a6cdb822e2463a13e5b0ec020028327c088d#diff-ed513a1e2f516c2c2808b598d7c364220a1ef0d950606ffa5fe2bc60a3e57bedR52), where I had to hardcode a reference to the directory containing the `keystore.ks` file on my filesystem. Does `mvn verify` have a way of exposing an environment variable that xqsuite could use to find the file stored in its src/test/resources directory? I'm not sure how to get the xqsuite to reference this binary file independently. 

I'm not actually certain that the xqsuite needs this resource. The original tests used keystore.ks in the [tests for crypto:generate-signature](https://github.com/eXist-db/crypto-exist-java-lib/blob/baebcc094044c882fde329e4667a193fcbe62469/src/test/java/org/expath/exist/crypto/xquery/generateEnvelopedDigitalSignature.xq#L35) and [crypto:validate-signature](https://github.com/eXist-db/crypto-exist-java-lib/blob/baebcc094044c882fde329e4667a193fcbe62469/src/test/java/org/expath/exist/crypto/xquery/validateEnvelopedDigitalSignature.xq#L32), but it doesn't appear to actually use them. Can we really jettison this resource and expect the tests of these functions to perform correctly? 

@nsincaglia Do you use the `crypto:generate-signature` or `crypto:validate-signature` functions? Do you have any working code that we could look at to see how these functions are supposed to work? The existing tests are a bit ambiguous.

**Comment by joewiz** [comment]
BaseX's tests may shed some light on expected behavior:
- https://github.com/BaseXdb/basex/blob/382c8097afb1ec5bac1e9511a2287686c33f669d/basex-tests/src/test/java/org/basex/FNCryptoTest.java
- https://github.com/BaseXdb/basex/blob/382c8097afb1ec5bac1e9511a2287686c33f669d/basex-core/src/test/java/org/basex/query/func/CryptoModuleTest.java

**Comment by line-o** [comment]
Interestingly, the tests in baseX generate the necessary signatures. I do like that approach a lot.

**Comment by adamretter** [comment]
> The xqsuite has one remaining problem on line 52,

I have fixed this now, it just needs to be in the correct Java classpath, then you can use `resource:` like URI in eXist-db to retrieve it.

**Comment by adamretter** [comment]
@joewiz @line-o As a first iteration, I think this is  now ready to merge.

**Comment by windauer** [comment]
@adamretter thanks a lot, looks good to me.

**Pull request merged**
