### PR TITLE
Branch for eXist 5.3.0

### PR DESCRIPTION
**Pull request by claudius108**

### CODE REVIEW

**Comment by adamretter** [comment]
@claudius108 Something doesn't seem quite right with this PR... from which branch are you trying to send the updates? Perhaps I could help?

**Comment by claudius108** [comment]
I wanted a PR from claudius108:eXist-5.3.0 to eXist-db:eXist-5.3.0, but I did to eXist-db:master.

**Comment by joewiz** [comment]
@claudius108 I see there are some conflicts. Will you be able to address this, or do you need assistance?

**Comment by claudius108** [comment]
Hi, 

There are some changes that I have to include in my branch. I will try to do this.

**Comment by line-o** [comment]
These to functions are duplicates in an XQuery context because their types are not taken into account only the number of arguments:

```java
    arity(
        FS_GENERATE_SIGNATURE_PARAM_DATA,
        FS_GENERATE_SIGNATURE_PARAM_CANONICALIZATION_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_DIGEST_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_NAMESPACE_PREFIX,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_TYPE,
        FS_GENERATE_SIGNATURE_PARAM_XPATH
    ),
    arity(
        FS_GENERATE_SIGNATURE_PARAM_DATA,
        FS_GENERATE_SIGNATURE_PARAM_CANONICALIZATION_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_DIGEST_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_NAMESPACE_PREFIX,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_TYPE,
        FS_GENERATE_SIGNATURE_PARAM_DIGITAL_CERTIFICATE
    ),

```

**Comment by line-o** [comment]
These are the signatures that the baseX implementation provides:

https://docs.basex.org/wiki/Cryptographic_Module

```xquery
crypto:generate-signature(
  $input as node(), 
  $canonicalization as xs:string, 
  $digest as xs:string, 
  $signature as xs:string, 
  $prefix as xs:string, 
  $type as xs:string
) as node()
```

```xquery
crypto:generate-signature(
  $input as node(),
  $canonicalization as xs:string,
  $digest as xs:string,
  $signature as xs:string,
  $prefix as xs:string,
  $type as xs:string,
  $xpath as xs:string,
  $certificate as node()
) as node()
```

```xquery
crypto:generate-signature(
  $input as node(),
  $canonicalization as xs:string,
  $digest as xs:string,
  $signature as xs:string,
  $prefix as xs:string,
  $type as xs:string,
  $ext as item()
) as node()
```

**Comment by line-o** [comment]
this signature of generate-signature should expect 8 parameters instead of 7
```
arity(
        FS_GENERATE_SIGNATURE_PARAM_DATA,
        FS_GENERATE_SIGNATURE_PARAM_CANONICALIZATION_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_DIGEST_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_ALGORITHM,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_NAMESPACE_PREFIX,
        FS_GENERATE_SIGNATURE_PARAM_SIGNATURE_TYPE,
        == Missing XPATH ==,
        FS_GENERATE_SIGNATURE_PARAM_DIGITAL_CERTIFICATE
    ),
```
```
crypto:generate-signature(
  $input as node(),
  $canonicalization as xs:string,
  $digest as xs:string,
  $signature as xs:string,
  $prefix as xs:string,
  $type as xs:string,
  $xpath as xs:string,
  $certificate as node()
) as node()
```

**Comment by line-o** [comment]
What are all these empty files for?

**Comment by joewiz** [comment]
Related: https://github.com/expath/expath-cg/issues/132.

**Comment by line-o** [comment]
development will be picked up by the existdb community

**Pull request closed without merging**
